Fix for 'random'
At least on my Archlinux system (no Raspberry Pi) I get the following error message:

File "/usr/lib/python2.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 319, in connect
cmd = 'connect {0} {1}'.format(self._address, address_type.name)
AttributeError: 'str' object has no attribute 'name'

I took a look at the example in the pygatt repo and pygatt.BLEAddressType.random is used instead of 'random'
Exchanging it resolves the error for me.